/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Objetos.Audio;
import Objetos.Video;
import Videos.Formato3GP;
import Videos.FormatoAVI;
import Videos.FormatoFLV;
import Videos.FormatoMP4;
import Videos.IFVideo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class JVideoToVideo extends javax.swing.JDialog {

    private static String NAME_ARCHIVE_INPUT = "";
    private static String NAME_ADDRESS_ARCHIVE_INPUT = "";
    private static String NAME_ARCHIVE_OUTPUT = "";
    private static String NAME_ADDRESS_ARCHIVE_OUTPUT = "";
    private static IFVideo formato;
    private String extensao = "";
    private boolean confirma = false;
    private String[] codecsVideo;
    private String[] codecsAudio;
    private Audio sound;
    private Video video;

    /**
     * Creates new form TelaVideoToVideo
     *
     * @param parent
     * @param modal
     * @param extensao
     * @param output
     */
    public JVideoToVideo(java.awt.Frame parent, boolean modal, String extensao, String output) {

        super(parent, modal);
        initComponents();

        NAME_ADDRESS_ARCHIVE_OUTPUT = output;
        jTextField1.setText(NAME_ADDRESS_ARCHIVE_OUTPUT);

        this.extensao = extensao;
        jComboBox2.removeAll();
        jComboBox3.removeAll();

        switch (extensao) {
            case "mp4":
                codecsVideo = new String[]{"mpeg4", "libxvid"};
                codecsAudio = new String[]{"libfaac"};
                jComboBox2.setModel(new DefaultComboBoxModel(codecsVideo));
                jComboBox3.setModel(new DefaultComboBoxModel(codecsAudio));
                break;
            case "3gp":
                codecsVideo = new String[]{"mpeg4", "libxvid"};
                codecsAudio = new String[]{"libfaac"};
                jComboBox2.setModel(new DefaultComboBoxModel(codecsVideo));
                jComboBox3.setModel(new DefaultComboBoxModel(codecsAudio));
                break;
            case "flv":
                codecsVideo = new String[]{"flv"};
                codecsAudio = new String[]{"libmp3lame"};
                jComboBox2.setModel(new DefaultComboBoxModel(codecsVideo));
                jComboBox3.setModel(new DefaultComboBoxModel(codecsAudio));
                break;
            case "avi":
                codecsVideo = new String[]{"mpeg4", "libxvid"};
                codecsAudio = new String[]{"libmp3lame"};
                jComboBox2.setModel(new DefaultComboBoxModel(codecsVideo));
                jComboBox3.setModel(new DefaultComboBoxModel(codecsAudio));
                break;
            default:
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taxaBitsSeletor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        caixaInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        taxaSamplingSeletor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        taxaCanaisSeletor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        taxaBitsSeletor1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        taxaCanaisSeletor1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        taxaBitsSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "128", "256" }));
        taxaBitsSeletor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("Bits");

        jLabel1.setText("CONVERSÃO DE VÍDEOS");

        jLabel2.setText("Input:");

        jButton1.setText("Selecionar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Output:");

        jLabel7.setText("Taxa de Bits Áudio:");

        jLabel6.setText("Hertz");

        taxaSamplingSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8000", "11025", "16000", "22050", "32000", "37800", "44056", "44100", "47250", "48000", "50000", "50400", "88200", "96000", "176400", "192000", "352800", "2822400", "5644800", "11289600", "22579200" }));
        taxaSamplingSeletor.setSelectedIndex(7);
        taxaSamplingSeletor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Sampling Rate Áudio:");

        jLabel9.setText("Canais");

        taxaCanaisSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        taxaCanaisSeletor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setText("Canais Áudio:");

        jLabel11.setText("Taxa de Bits Vídeo:");

        taxaBitsSeletor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "128", "256" }));
        taxaBitsSeletor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setText("Bits");

        jLabel13.setText("Canais Vídeo:");

        taxaCanaisSeletor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        taxaCanaisSeletor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setText("Canais");

        jLabel17.setText("Codecs de Vídeo:");

        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel18.setText("Codecs de Áudio:");

        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel19.setText("Frames Por Segundo:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ok.png"))); // NOI18N
        jButton3.setText("Iniciar Conversão");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tamanho do vídeo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padrão", "320x240 Standard", "400x240 Mobile Standard", "480x320 Mobile Standard", "480x360 Mobile Standard", "720x480 HD Device", "1280x420 HD Device", "1920x1080 HD Device", "640x480 VGA", "800x600 SVGA", "1024x768 XVGA" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton2)
                        .addGap(154, 154, 154)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(123, 123, 123)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(13, 13, 13)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(taxaSamplingSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel6))
                                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(taxaCanaisSeletor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(taxaBitsSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel8))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel9))))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(taxaCanaisSeletor1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(taxaBitsSeletor1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel12))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel14))))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(caixaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(taxaBitsSeletor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(taxaBitsSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxaCanaisSeletor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(taxaCanaisSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel5)
                    .addComponent(taxaSamplingSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(78, 78, 78))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // TODO add your handling code here:
            JFileChooser j = new JFileChooser(System.getProperty("user.home") + "\\Desktop");
            switch (extensao) {
                case "avi":
                    j.setFileFilter(new FileNameExtensionFilter("Videos", "3gp", "mp4", "flv"));
                    break;
                case "3gp":
                    j.setFileFilter(new FileNameExtensionFilter("Videos", "avi", "mp4", "flv"));
                    break;
                case "mp4":
                    j.setFileFilter(new FileNameExtensionFilter("Videos", "avi", "3gp", "flv"));
                    break;
                case "flv":
                    j.setFileFilter(new FileNameExtensionFilter("Videos", "avi", "3gp", "mp4"));
                    break;
            }

            j.setAcceptAllFileFilterUsed(false);
            j.setApproveButtonText("Selecionar");
            Appearance.appearance(j);
            j.showOpenDialog(this);
            NAME_ADDRESS_ARCHIVE_INPUT = j.getCurrentDirectory().toString();
            String fileSelected = j.getSelectedFile().getAbsoluteFile().getName();
            NAME_ARCHIVE_INPUT = NAME_ARCHIVE_OUTPUT = "\\" + fileSelected.substring(0, fileSelected.indexOf("."));
            caixaInput.setText(j.getCurrentDirectory().toString() + "\\" + fileSelected);
            jTextField1.setText(NAME_ADDRESS_ARCHIVE_OUTPUT + NAME_ARCHIVE_INPUT + "." + extensao);
            
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JVideoToVideo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!(caixaInput.getText().isEmpty() || caixaInput.getText().equals(""))) {
            confirma = true;

            sound = new Audio(
                    "",
                    Integer.parseInt(taxaBitsSeletor.getSelectedItem().toString()) * 1000,
                    Integer.parseInt(taxaCanaisSeletor.getSelectedItem().toString()),
                    Integer.parseInt(taxaSamplingSeletor.getSelectedItem().toString()),
                    jComboBox3.getSelectedItem().toString()
            );
            video = new Video(
                    sound,
                    Integer.parseInt(taxaBitsSeletor1.getSelectedItem().toString()) * 1000,
                    Integer.parseInt("" + jSpinner1.getValue()),
                    extensao,
                    Integer.parseInt(taxaCanaisSeletor1.getSelectedItem().toString()),
                    jComboBox2.getSelectedItem().toString()
            );
            video.setNome(NAME_ARCHIVE_OUTPUT.substring(1));
            switch (extensao) {
                case "flv":
                    formato = new FormatoFLV();
                    break;
                case "mp4":
                    formato = new FormatoMP4();
                    break;
                case "3gp":
                    formato = new Formato3GP();
                    break;
                case "avi":
                    formato = new FormatoAVI();
                    break;
            }

            switch (jComboBox1.getSelectedItem().toString()) {
                case "Padrão":
                    break;
                case "320x240 Standard":
                    video.setResolucao(new Integer[]{320, 240});
                    break;
                case "400x240 Mobile Standard":
                    video.setResolucao(new Integer[]{400, 240});
                    break;
                case "480x320 Mobile Standard":
                    video.setResolucao(new Integer[]{480, 320});
                    break;
                case "480x360 Mobile Standard":
                    video.setResolucao(new Integer[]{480, 360});
                    break;
                case "720x480 HD Device":
                    video.setResolucao(new Integer[]{720, 480});
                    break;
                case "1280x420 HD Device":
                    video.setResolucao(new Integer[]{1280, 420});
                    break;
                case "1920x1080 HD Device":
                    video.setResolucao(new Integer[]{1920, 1080});
                    break;
                case "640x480 VGA":
                    video.setResolucao(new Integer[]{640, 480});
                    break;
                case "800x600 SVGA":
                    video.setResolucao(new Integer[]{800, 600});
                    break;
                case "1024x768 XVGA":
                    video.setResolucao(new Integer[]{1024, 768});
                    break;
            }

            formato.setVideo(video);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um arquivo de entrada!", "Aviso", 2);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caixaInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> taxaBitsSeletor;
    private javax.swing.JComboBox<String> taxaBitsSeletor1;
    private javax.swing.JComboBox<String> taxaCanaisSeletor;
    private javax.swing.JComboBox<String> taxaCanaisSeletor1;
    private javax.swing.JComboBox<String> taxaSamplingSeletor;
    // End of variables declaration//GEN-END:variables
    public boolean getConfirmacao() {
        return this.confirma;
    }

    public IFVideo getVideo() {
        return this.formato;
    }

    public Audio getAudio() {
        return this.sound;
    }

    public String getOutput() {
        return jTextField1.getText();
    }

    public String getInput() {
        return caixaInput.getText();
    }

}
