/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.VideoToAudio;
import Metodos.VideoToVideo;
import Objetos.Audio;
import Videos.IFVideo;
import it.sauronsoftware.jave.EncoderException;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.TitledBorder;

/**
 *
 * @author lucas
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private String input = "";
    private String output = "";
    private static String NAME_ADDRESS_ARCHIVE_OUTPUT = System.getProperty("user.home") + "\\" + "Desktop";

    private IFVideo VideoMp4;

    private IFVideo VideoAvi;

    private IFVideo VideoFlv;

    private IFVideo Video3gp;

    private File VideoMp3;
    private Audio soundmp3;

    private File VideoWav;
    private Audio soundwav;

    private ModeloLoading m;

    public TelaInicial() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/logo.jpg")).getImage());
        jTextField1.setText(NAME_ADDRESS_ARCHIVE_OUTPUT);
        jTextField2.setText(NAME_ADDRESS_ARCHIVE_OUTPUT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        mp3 = new javax.swing.JLabel();
        wav = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        painelMusica = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        avi = new javax.swing.JLabel();
        mp4 = new javax.swing.JLabel();
        flv = new javax.swing.JLabel();
        l3gp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelVideo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcoes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Vídeo e Áudio");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        mp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MP3.PNG"))); // NOI18N
        mp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mp3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mp3MouseExited(evt);
            }
        });

        wav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/WAV.PNG"))); // NOI18N
        wav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wavMouseExited(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(439, 102));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(439, 102));

        painelMusica.setBackground(new java.awt.Color(255, 255, 255));
        painelMusica.setMinimumSize(new java.awt.Dimension(420, 100));
        painelMusica.setLayout(new javax.swing.BoxLayout(painelMusica, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(painelMusica);

        jButton1.setText("LIMPAR ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pasta de Destino:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wav, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mp3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(mp3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(wav, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Conversão Para Áudio", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        avi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AVI.PNG"))); // NOI18N
        avi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aviMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aviMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aviMouseExited(evt);
            }
        });

        mp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MP4.PNG"))); // NOI18N
        mp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mp4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mp4MouseExited(evt);
            }
        });

        flv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FLV.PNG"))); // NOI18N
        flv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flvMouseExited(evt);
            }
        });

        l3gp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/3GP.PNG"))); // NOI18N
        l3gp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l3gp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3gpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l3gpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3gpMouseExited(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        painelVideo.setBackground(new java.awt.Color(255, 255, 255));
        painelVideo.setAutoscrolls(true);
        painelVideo.setMinimumSize(new java.awt.Dimension(420, 100));
        painelVideo.setLayout(new javax.swing.BoxLayout(painelVideo, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(painelVideo);

        jButton2.setText("LIMPAR ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pasta de Destino:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mp4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3gp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(mp4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(flv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(avi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(l3gp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Conversão Para Vídeo", jPanel2);

        opcoes.setText("Opções");
        opcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("Alterar Pasta de Destino");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        opcoes.add(jMenuItem1);

        jMenuBar1.add(opcoes);

        sobre.setText("Sobre");
        sobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem2.setText("Equipe de Desenvolvimento");
        jMenuItem2.setContentAreaFilled(false);
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        sobre.add(jMenuItem2);

        jMenuItem3.setText("Repositório do Projeto");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        sobre.add(jMenuItem3);

        jMenuBar1.add(sobre);

        sair.setText("Sair");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Equipe ACL.\nTodos os direitos reservados.", "Equipe ACL", 1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Desktop desk = java.awt.Desktop.getDesktop();
        try {
            desk.browse(new java.net.URI("http://www.github.com/EquipeACL/SistemasMultimidia"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp3MouseClicked
        JVideoToAudio vta = new JVideoToAudio(this, true, "mp3", NAME_ADDRESS_ARCHIVE_OUTPUT);

        vta.setVisible(true);
        if (vta.getConfirmacao()) {
            VideoMp3 = vta.getVideo();
            soundmp3 = vta.getAudio();
            output = vta.getOutput();
            loadMusic(VideoMp3.getPath());
            new Thread(converterParaMp3).start();
        }
    }//GEN-LAST:event_mp3MouseClicked

    private void mp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp3MouseEntered
        mp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MP3-hover.PNG")));
    }//GEN-LAST:event_mp3MouseEntered

    private void mp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp3MouseExited
        mp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MP3.PNG")));
    }//GEN-LAST:event_mp3MouseExited

    private void wavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wavMouseClicked
        JVideoToAudio vta = new JVideoToAudio(this, true, "wav", NAME_ADDRESS_ARCHIVE_OUTPUT);
        vta.setVisible(true);
        if (vta.getConfirmacao()) {
            VideoWav = vta.getVideo();
            soundwav = vta.getAudio();
            output = vta.getOutput();
            loadMusic(VideoWav.getPath());
            new Thread(converterParaWav).start();
        }
    }//GEN-LAST:event_wavMouseClicked

    private void wavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wavMouseEntered
        wav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/WAV-hover.PNG")));
    }//GEN-LAST:event_wavMouseEntered

    private void wavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wavMouseExited
        wav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/WAV.PNG")));
    }//GEN-LAST:event_wavMouseExited

    private void aviMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aviMouseEntered
        avi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AVI-hover.PNG")));
    }//GEN-LAST:event_aviMouseEntered

    private void aviMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aviMouseExited
        avi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AVI.PNG")));
    }//GEN-LAST:event_aviMouseExited

    private void mp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp4MouseClicked
        JVideoToVideo vta = new JVideoToVideo(this, true, "mp4", NAME_ADDRESS_ARCHIVE_OUTPUT);
        vta.setVisible(true);
        if (vta.getConfirmacao()) {
            VideoMp4 = vta.getVideo();
            input = vta.getInput();
            output = vta.getOutput();
            loadVideo();
            new Thread(converterParaMp4).start();
        }
    }//GEN-LAST:event_mp4MouseClicked

    private void mp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp4MouseEntered
        mp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MP4-hover.PNG")));
    }//GEN-LAST:event_mp4MouseEntered

    private void mp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp4MouseExited
        mp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MP4.PNG")));
    }//GEN-LAST:event_mp4MouseExited

    private void flvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flvMouseEntered
        flv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FLV-hover.PNG")));
    }//GEN-LAST:event_flvMouseEntered

    private void flvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flvMouseExited
        flv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FLV.PNG")));
    }//GEN-LAST:event_flvMouseExited

    private void l3gpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3gpMouseEntered
        l3gp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/3GP-hover.PNG")));
    }//GEN-LAST:event_l3gpMouseEntered

    private void l3gpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3gpMouseExited
        l3gp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/3GP.PNG")));
    }//GEN-LAST:event_l3gpMouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            JFileChooser j = new JFileChooser(System.getProperty("user.home")+"\\Desktop");
            j.setApproveButtonText("Selecionar");
            j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            j.setFileHidingEnabled(false);
            Appearance.appearance(j);
            j.showOpenDialog(this);
            NAME_ADDRESS_ARCHIVE_OUTPUT = j.getSelectedFile().toString();
             jTextField1.setText(NAME_ADDRESS_ARCHIVE_OUTPUT);
             jTextField2.setText(NAME_ADDRESS_ARCHIVE_OUTPUT);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void aviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aviMouseClicked
        // TODO add your handling code here:
        JVideoToVideo vta = new JVideoToVideo(this, true, "avi", NAME_ADDRESS_ARCHIVE_OUTPUT);
        vta.setVisible(true);
        if (vta.getConfirmacao()) {
            VideoAvi = vta.getVideo();
            input = vta.getInput();
            output = vta.getOutput();
            loadVideo();
            new Thread(converterParaAvi).start();
        }
    }//GEN-LAST:event_aviMouseClicked

    private void flvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flvMouseClicked
        // TODO add your handling code here:
        JVideoToVideo vta = new JVideoToVideo(this, true, "flv", NAME_ADDRESS_ARCHIVE_OUTPUT);
        vta.setVisible(true);
        if (vta.getConfirmacao()) {
            VideoFlv = vta.getVideo();
            input = vta.getInput();
            output = vta.getOutput();
            loadVideo();
            new Thread(converterParaFlv).start();
        }
    }//GEN-LAST:event_flvMouseClicked

    private void l3gpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3gpMouseClicked
        // TODO add your handling code here:
        JVideoToVideo vta = new JVideoToVideo(this, true, "3gp", NAME_ADDRESS_ARCHIVE_OUTPUT);
        vta.setVisible(true);
        if (vta.getConfirmacao()) {
            Video3gp = vta.getVideo();
            input = vta.getInput();
            output = vta.getOutput();
            loadVideo();
            new Thread(converterPara3gp).start();
        }
    }//GEN-LAST:event_l3gpMouseClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        painelVideo.removeAll();
        painelVideo.repaint();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        painelMusica.removeAll();
        painelMusica.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avi;
    private javax.swing.JLabel flv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel l3gp;
    private javax.swing.JLabel mp3;
    private javax.swing.JLabel mp4;
    private javax.swing.JMenu opcoes;
    private javax.swing.JPanel painelMusica;
    private javax.swing.JPanel painelVideo;
    private javax.swing.JMenu sair;
    private javax.swing.JMenu sobre;
    private javax.swing.JLabel wav;
    // End of variables declaration//GEN-END:variables
    private Runnable converterParaMp3 = new Runnable() {
        public void run() {
            try {
                VideoToAudio.convertToAudio(soundmp3, VideoMp3.getPath().replace('\\', '/'), output.replace('\\', '/'));
            } catch (IllegalArgumentException | EncoderException | IOException ex) {
                Logger.getLogger(VideoToAudio.class.getName()).log(Level.SEVERE, null, ex);
            }

            end();
        }
    };

    private Runnable converterParaWav = new Runnable() {
        public void run() {
            try {
                VideoToAudio.convertToAudio(soundwav, VideoWav.getPath().replace('\\', '/'), output.replace('\\', '/'));
            } catch (IllegalArgumentException | EncoderException | IOException ex) {
                Logger.getLogger(VideoToAudio.class.getName()).log(Level.SEVERE, null, ex);
            }
            end();
        }
    };

    private Runnable converterParaMp4 = new Runnable() {
        public void run() {
            try {
                VideoToVideo.convert(input, output, VideoMp4);
            } catch (IllegalArgumentException | EncoderException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            end();
        }
    };

    private Runnable converterParaAvi = new Runnable() {
        public void run() {
            try {
                VideoToVideo.convert(input, output, VideoAvi);
            } catch (IllegalArgumentException | EncoderException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            end();
        }
    };

    private Runnable converterPara3gp = new Runnable() {
        public void run() {
            try {
                VideoToVideo.convert(input, output, Video3gp);
            } catch (IllegalArgumentException | EncoderException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            end();
        }

    };

    private Runnable converterParaFlv = new Runnable() {
        public void run() {
            try {
                VideoToVideo.convert(input, output, VideoFlv);
            } catch (IllegalArgumentException | EncoderException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            end();
        }
    };

    public void loadMusic(String entrada) {
        m = new ModeloLoading();
        m.setEntrada(entrada);
        m.setSaida(output);
        m.setLoading("loading.gif");
        painelMusica.add(m);
    }

    public void loadVideo() {
        m = new ModeloLoading();
        m.setEntrada(input);
        m.setSaida(output);
        m.setLoading("loading.gif");
        painelVideo.add(m);
    }

    public void end() {
        m.setLoading("concluido.png");
    }

}
