/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Objetos.Audio;
import it.sauronsoftware.jave.EncoderException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import Metodos.VideoToAudio;

/**
 *
 * @author lucas
 */
public class TelaVideoToAudio extends javax.swing.JFrame {

    private static String NAME_ARCHIVE_INPUT = "";
    private static String NAME_ADDRESS_ARCHIVE_INPUT = "";
    private static String NAME_ARCHIVE_OUTPUT = "";
    private static String NAME_ADDRESS_ARCHIVE_OUTPUT = System.getProperty("user.home") + "\\" + "Desktop";

    /**
     * Creates new form NewJFrame
     */
    public TelaVideoToAudio() {
        initComponents();
        mp3.setSelected(true);
        textoOutput.setText(NAME_ADDRESS_ARCHIVE_OUTPUT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoInput = new javax.swing.JTextField();
        mp3 = new javax.swing.JRadioButton();
        wav = new javax.swing.JRadioButton();
        inputNome = new javax.swing.JLabel();
        outputNome = new javax.swing.JLabel();
        textoOutput = new javax.swing.JTextField();
        botaoInput = new javax.swing.JButton();
        taxaBitsSeletor = new javax.swing.JComboBox<>();
        taxBitsNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taxaCanaisSeletor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        taxaSamplingSeletor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoInputActionPerformed(evt);
            }
        });

        mp3.setBackground(new java.awt.Color(255, 255, 255));
        mp3.setText("mp3");
        mp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mp3ActionPerformed(evt);
            }
        });

        wav.setBackground(new java.awt.Color(255, 255, 255));
        wav.setText("wav");
        wav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wavActionPerformed(evt);
            }
        });

        inputNome.setText("Input:");

        outputNome.setText("Output:");

        botaoInput.setBackground(new java.awt.Color(255, 255, 255));
        botaoInput.setText("Diretório");
        botaoInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInputActionPerformed(evt);
            }
        });

        taxaBitsSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "128", "256" }));
        taxaBitsSeletor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        taxBitsNome.setText("Taxa de Bits:");

        jLabel1.setText("Bits");

        jLabel2.setText("CONVERTER VÍDEO PARA ÁUDIO");

        jLabel3.setText("Canais:");

        taxaCanaisSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        taxaCanaisSeletor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Canais");

        jLabel5.setText("Sampling Rate:");

        taxaSamplingSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8000", "11025", "16000", "22050", "32000", "37800", "44056", "44100", "47250", "48000", "50000", "50400", "88200", "96000", "176400", "192000", "352800", "2822400", "5644800", "11289600", "22579200" }));
        taxaSamplingSeletor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setText("Hertz");

        jButton1.setText("Iniciar Conversão");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(mp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wav)
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(taxBitsNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(outputNome)
                                .addComponent(inputNome))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoInput)
                                    .addComponent(textoOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoInput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(taxaCanaisSeletor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taxaBitsSeletor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(taxaSamplingSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(223, 223, 223))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mp3)
                    .addComponent(wav))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputNome)
                    .addComponent(textoOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxaBitsSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taxBitsNome)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taxaCanaisSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(taxaSamplingSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInputActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            JFileChooser j = new JFileChooser(System.getProperty("user.home"));
            j.setApproveButtonText("Selecionar");
            Appearance.appearance(j);
            j.showOpenDialog(this);
            NAME_ADDRESS_ARCHIVE_INPUT = j.getCurrentDirectory().toString();
            String fileSelected = j.getSelectedFile().getAbsoluteFile().getName();
            NAME_ARCHIVE_INPUT = NAME_ARCHIVE_OUTPUT = "\\" + fileSelected.substring(0, fileSelected.indexOf("."));
            textoInput.setText(j.getCurrentDirectory().toString() + "\\" + fileSelected);
            textoOutput.setText(NAME_ADDRESS_ARCHIVE_OUTPUT + NAME_ARCHIVE_INPUT + ".mp3");
            mp3.setSelected(true);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VideoToAudio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_botaoInputActionPerformed

    private void mp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mp3ActionPerformed
        wav.setSelected(false);
        if (!textoInput.getText().isEmpty() && mp3.isSelected()) {
            textoOutput.setText(NAME_ADDRESS_ARCHIVE_OUTPUT + NAME_ARCHIVE_OUTPUT + ".mp3");
        }

    }//GEN-LAST:event_mp3ActionPerformed

    private void wavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wavActionPerformed
        // TODO add your handling code here:
        mp3.setSelected(false);
        if (!textoInput.getText().isEmpty() && wav.isSelected()) {
            textoOutput.setText(NAME_ADDRESS_ARCHIVE_OUTPUT + NAME_ARCHIVE_OUTPUT + ".wav");
        }
    }//GEN-LAST:event_wavActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//String formato, String input, String output, int taxaBits, int canais, int samplingRate
        File video = new File(textoInput.getText());
        Audio sound;
        if(mp3.isSelected()){
            sound = new Audio(
                    
                    "mp3",
                    Integer.parseInt(taxaBitsSeletor.getSelectedItem().toString())*1000,
                    Integer.parseInt(taxaCanaisSeletor.getSelectedItem().toString()),
                    Integer.parseInt(taxaSamplingSeletor.getSelectedItem().toString()), ""
            );
        } else {
            sound = new Audio(
                    
                    "wav",
                    Integer.parseInt(taxaBitsSeletor.getSelectedItem().toString())*1000,
                    Integer.parseInt(taxaCanaisSeletor.getSelectedItem().toString()),
                    Integer.parseInt(taxaSamplingSeletor.getSelectedItem().toString()),""
            );
        }
        
        try {
            VideoToAudio.convertToAudio(sound,textoInput.getText().replace('\\', '/'),textoOutput.getText().replace('\\', '/'));
        } catch (IllegalArgumentException | EncoderException | IOException ex) {
            Logger.getLogger(VideoToAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void textoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoInputActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInput;
    private javax.swing.JLabel inputNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mp3;
    private javax.swing.JLabel outputNome;
    private javax.swing.JLabel taxBitsNome;
    private javax.swing.JComboBox<String> taxaBitsSeletor;
    private javax.swing.JComboBox<String> taxaCanaisSeletor;
    private javax.swing.JComboBox<String> taxaSamplingSeletor;
    private javax.swing.JTextField textoInput;
    private javax.swing.JTextField textoOutput;
    private javax.swing.JRadioButton wav;
    // End of variables declaration//GEN-END:variables
}
